name: assignment_2
description: Fetch and display mock exoplanet API data with null safety, Future, and async/await.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '^3.0.0'

dependencies:
dev_dependencies:
